data_dir: &DIR ../data/toy/
tweet_file: !join [*DIR, input/tweets.txt]
result_dir: !join [*DIR, output/]
case_dir: !join [*DIR, output/case/]
model_dir: !join [*DIR, model/]
model_embeddings_dir: !join [*DIR, model/embeddings/]
model_pickled_path: !join [*DIR, model/pickled.model]

voca_min: 0
voca_max: 20000
dim: 10
negative: 1
alpha: 0.02 # learning rate
epoch: 1
nt_list: ['w','l','t']
predict_type: ['w', 'l', 't']
test_size: 100
kernel_nb_num: 1 # used for efficiency reason (requested by fast k-nearest-neighbor search)
bandwidth_l: 0.001 # used for detecting spatial hotpsots
bandwidth_t: 10.0 # used for detecting temporal hotpsots
kernel_bandwidth_l: 0.001 # used for spatial smoothing
kernel_bandwidth_t: 1000.0 # used for temporal smoothing
second_order: 0
use_context_vec: 1

